///<reference path="../src/html.js">
///<reference path="../src/css.js">
///<reference path="./template.js">

const schedule = (() => {
    return [
        template.page(0)(
            "Schedule",
            html.div({ class: ["text-sm"] })([
                html.table({ style: [css.w.percent(100)] })([
                    html.tr()([
                        html.td({ style: [css.w.percent(25)] })``,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`9`,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`10`,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`11`,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`12`,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`13`,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`14`,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`15`,
                        html.td({ style: [css.w.percent(9.375), css.tx.center()] })`16`,
                    ]),
                    html.tr()([
                        html.td()`Prepare the Dataset`,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                    ]),
                    html.tr()([
                        html.td()`VQ-MHA-U-Net`,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                    ]),
                    html.tr()([
                        html.td()`Oracle Model`,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                    ]),
                    html.tr()([
                        html.td()`Experiment A`,
                        html.td()``,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                    ]),
                    html.tr()([
                        html.td()`Model based on VQ-VAE-2`,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                        html.td()``,
                    ]),
                    html.tr()([
                        html.td()`Change the model of Encoder&Decoder`,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                        html.td()``,
                    ]),
                    html.tr({ style: [css.bg.color(255, 222, 222)] })([
                        html.td({ style: [css.tx.color(255, 0, 102)] })`Challenge`,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                        html.td()``,
                    ]),
                    html.tr()([
                        html.td()`Experiment B`,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                        html.td()``,
                    ]),
                    html.tr()([
                        html.td()`Demo`,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td()``,
                        html.td({ style: [css.bg.color(255, 0, 102)] })``,
                    ]),
                ])
            ]),
        ),
    ]
})()